version: '2'
services:
  app:
    build: app
    image: app:0.0.1
    container_name: app
    ports:
      - "8082:8080"
    privileged: true
    networks:
      - my_network
    volumes:
      - ./app:/app
    environment:
      JAR_TARGET: app-0.0.1.jar
  express:
    build: express/node
    image: node-express-dev:1.0
    container_name: express
    tty: true
    depends_on:
      - app
    volumes:
      - ./express/node/app:/app
    ports:
      - "8081:3001"
    privileged: true
    networks:
      - my_network
  gateway:
    build: gateway
    image: gateway-app/boot:0.0.1
    container_name: gateway
    ports:
      - "8080:8080"
    volumes:
      - ./gateway:/app
    tty: true
    depends_on:
      - app
      - express
    links:
      - app
      - express
    privileged: true
    networks:
      - my_network
    environment:
      JAR_TARGET: gs-gateway-0.1.0.jar
networks:
  my_network:
    external: true
